### ISSUE TITLE
itemStyle属性是不是不起作用

### ISSUE THREAD

**Issue by jasonlvg** [lesliesam/react-native-wheel-picker#1]

**Comment by lesliesam** [comment]
你设置的itemStyle里面哪些属性不起作用？
你可以参考下面代码设置文字颜色和字体大小。
<Picker style={{width: 150, height: 180}}
          selectedValue={this.state.selectedItem}
          itemStyle={{color:"white", fontSize:26}}>

**Comment by anysome** [comment]
两个属性都不起作用

**Comment by lesliesam** [comment]
我试了下，Android下确实没效果，一会儿我修改一下。

**Comment by lesliesam** [comment]
@anysome 已经修改好了，你试下。
