### ISSUE TITLE
Change 'modify MainActivity' to 'modify 'MainApplication.java' in readme

### ISSUE THREAD

**Issue by Osipion** [lesliesam/react-native-wheel-picker#15]
The [readme](https://github.com/lesliesam/react-native-wheel-picker/blob/master/README.md#how-to-use) currently says to add a `getPackages()` method to "MainActivity". This should probably be "MainApplication.java".

**Comment by lesliesam** [comment]
@Osipion You are right, that was the old style. Let me update it.
