### ISSUE TITLE
Not able to change fontFamily

### ISSUE THREAD

**Issue by GroupXTech** [lesliesam/react-native-wheel-picker#17]
Android doesn't allow changing the font to anything else but the system default.
Can you add this in?

Thanks

**Comment by MostafaEbrahimi** [comment]
Hi !
You can change font by prop `itemTextFontFamily = {"font_name"}`
<br>
```
<WheelPicker

            isCurved={false}
            isCyclic
            itemTextFontFamily = {"font_name"}
            ....
          />
```

**Comment by jenskuhrjorgensen** [comment]
Hi @GroupXTech - did the proposed solution work for you? I still cannot change the font family of the picker items on Android.

**Comment by SurajMDurgad** [comment]
Nope the above solution doesn't work!
Any update on this?
@lesliesam

**Comment by SurajMDurgad** [comment]
I found the solution, enter your font styles inside itemStyle - 
itemStyle={{fontSize:normalize(14), color: '#000', fontFamily: Platform.OS === 'ios' ? 'Montserrat-Semibold' : 'montserrat_semibold'}}

**Comment by mostafaebrahimi** [comment]
@jenskuhrjorgensen Did you define your custom font in android ?
use this link for [custom font android](https://stackoverflow.com/questions/3651086/android-using-custom-font?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

**Comment by jenskuhrjorgensen** [comment]
@MostafaEbrahimi I did yes, and they were defined like this in assets/fonst:
```
const fonts = {
    muliExtraLight: "Muli-ExtraLight",
    muliLight: "Muli-Light",
    muliSemiBold: "Muli-SemiBold",
    muliRegular: "Muli-Regular",
    muliBold: "Muli-Bold",
};

export default fonts;
```
And used like this (which works on iOS): 

```
<Picker
                style={styles.picker}
                selectedValue={selectedValue.order}
                itemStyle={{
                    color: "blue",
                    fontSize: 50,
                    fontFamily: fonts.muliLight,
                }}
/>
```

To identify whether I define the custom fonts correct or not, I tried to just set the font to one of the fonts available [out of the box](https://github.com/react-native-training/react-native-fonts), but also to no avail. I also tried to set the font family using your earlier proposed solution without using the `itemStyle` prop and instead using the `itemTextFontFamily` prop:
```
<Picker
                style={styles.picker}
                selectedValue={selectedValue.order}
                itemStyle={{
                    color: "blue",
                    fontSize: 50,
                }}
                itemTextFontFamily={"sans-serif-light"}
/>
```

**Comment by mostafaebrahimi** [comment]
@jenskuhrjorgensen  Did you code android before ? set TextView font using fontface .if it works correctly then go to react native.
[fontface android](https://stackoverflow.com/questions/29876068/set-font-face-in-android?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)
