### ISSUE TITLE
能不能只在用户选中时才触发onValueChange

### ISSUE THREAD

**Issue by anysome** [lesliesam/react-native-wheel-picker#2]
我会在用户选中时触发隐藏picker，在ios就是这么做完全没问题。
可是用这个在安卓上，就会因为设置selectedValue时触发onValueChange，变成刚显示又隐藏了。

**Comment by lesliesam** [comment]
没明白你是什么意思，程序确实是在选中时才触发ItemSelectedEvent。你遇到了什么问题？

**Comment by anysome** [comment]
我用了一个touchable，点击的时候触发显示picker并设置默认值，并且在picker的onValueChange触发隐藏picker。在ios上不会显示的时候就触发onValueChange，但安卓用这个插件就会触发onValueChange，导致显示了马上隐藏。
[https://github.com/anysome/objective/blob/master/app/widgets/OptionsPicker.android.js](https://github.com/anysome/objective/blob/master/app/widgets/OptionsPicker.android.js)

**Comment by lesliesam** [comment]
哦，明白了。不过这个不太好修过，这属于底层第三发的lib的代码（https://github.com/AigeStudio/WheelPicker ）

**Comment by anysome** [comment]
好的，谢谢
