### ISSUE TITLE
将react-native-picker中的react-native-picker-android组件替换成react-native-wheel-picker会报错，找了好久问题的原因，没能解决，能帮忙看下吗

### ISSUE THREAD

**Issue by jasonlvg** [lesliesam/react-native-wheel-picker#3]

**Comment by lesliesam** [comment]
react-native-picker这个组件我也用过，非常卡，性能有问题的。
一般你照着我的example写不会出什么错误的。
如果有需要，你把主要代码贴出来，错误贴出来，我帮你看看。

**Comment by jasonlvg** [comment]
你的example没有问题，我这里已经能够使用，但是我想实现三级联动的效果，不知道有没有更好的解决方案

**Comment by lesliesam** [comment]
三级联动，你能具体解释下含义吗？我不太明白。

**Comment by jasonlvg** [comment]
类似于省、市、区的选择
在示例程序中，我修改onAddItem函数，改变itemList的内容如下：
onAddItem: function() {
    //var name = '司马懿'
   // if (this.state.itemList.indexOf(name) == -1) {
    //  this.state.itemList.push(name)
   // }
    this.setState({
      itemList：[1, 2, 3, 4],
      //selectedItem: this.state.itemList.indexOf(name),
      selectedItem: 1,
    })
  },
会报错：

![error](https://cloud.githubusercontent.com/assets/12878649/15427135/831d6eb6-1ec5-11e6-9cb8-fd92f329ed56.jpg)
我是在Android环境下跑的

**Comment by HiZhenyu** [comment]
我的分支已帮你解决这个问题。
