### ISSUE TITLE
README.md does not include import com.zyu.ReactNativeWheelPickerPackage; 

### ISSUE THREAD

**Issue by pietgk** [lesliesam/react-native-wheel-picker#4]
it would make it a bit easier to install the package if the import in MainActivity.java was specified.
i assume it should be:
import com.zyu.ReactNativeWheelPickerPackage;

but i get a ...../MainActivity.java:8: error: package com.zyu does not exist
import com.zyu.ReactNativeWheelPickerPackage;
^

any hints or an example project to compare with would be great.

Thx

**Comment by lesliesam** [comment]
Did you forgot to included 'react-native-wheel-picker' into your project? Seems so, otherwise com.zyu should be exist.

**Comment by pietgk** [comment]
after also adding

    compile project(':react-native-wheel-picker')

into build.cradle it works.

so adding both to the readme would help future users not very familiar with gradle :-)

**Comment by lesliesam** [comment]
Yes, right. Good suggestion.
