### ISSUE TITLE
hello,那个react-native-wheel-picker中间的item怎么设置高度

### ISSUE THREAD

**Issue by andylidong** [lesliesam/react-native-wheel-picker#6]

**Comment by lesliesam** [comment]
不能设置高度，iOS原生控件不支持设置，所以是设置不了的。

**Comment by andylidong** [comment]
问一下那个，itemStyle : {color:"black", fontSize:26},设置之后，字体的大小在不同的机器上显示的不同，怎么控制

**Comment by andylidong** [comment]
可以在setTextSize的时候加上单位吗，picker.setTextSize(TypedValue.COMPLEX_UNIT_SP,size);

**Comment by lesliesam** [comment]
一般在style里面乘上一个系数：itemStyle : {color:"black", fontSize:26*windowHeightCoefficient}

**Comment by andylidong** [comment]
itemStyle : {color:"black", fontSize: 9 * PixelRatio.get()},
itemSpace: 7 * PixelRatio.get(),
根据屏幕的分辨率来处理的

**Comment by lesliesam** [comment]
对，这样写更好了。
