### ISSUE TITLE
[iOS] Picker always return to default option after select another

### ISSUE THREAD

**Issue by sebackend** [lesliesam/react-native-wheel-picker#62]
This error only occurs on iOS, in Android never happens. After selecting an option, the list automatically returns to the initial option (the value is updated successfully, but the selector changes again, as if it had been dragged by me twice).

I will upload a gif later to show this in more detail.

**Comment by danielkeithw** [comment]
This happens to me also.  It only seems to happen if the list of items is accessed (refreshed even with the same values)

**Comment by sebackend** [comment]
I will close this issue, because i didn't realize that the values in the picker was set from props instead of local state...my bad.
